version: "3.6"

services:

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./setup_db/stscr/:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:        ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:             ${MYSQL_DATABASE}
  
  drf-server:
    container_name: DRF-server
    build: ./server
    depends_on:
      - db
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./server/:/server/
    environment:
      APP_PORT: ${APP_PORT}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

      MYSQL_HOST:           ${MYSQL_HOST}
      MYSQL_PORT:           ${MYSQL_PORT}
      MYSQL_DATABASE:       ${MYSQL_DATABASE}
      MYSQL_USER:           ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}